//! ALL RED COMMENTED SECTIONS ARE PLACES WHERE POTENTIAL CHANGES ARE NEEDED BASED UPON YOUR APPLICATION
const mongoose = require('mongoose');

//? SETTING UP MongoDB SCHEMA
//! Update playerSchema below for a name that fits your application. Also update any fields below for the type of schema such as changing team points with a type of number instead of string, etc. Also, you can add as many schema fields as needed.
const scoresSchema = new mongoose.Schema({
  season: {
    type: String,
    required: true,
  },
  gameDate: {
    type: String,
    required: true,
  },
  venue: {
    type: String,
    required: true,
  },
  gameTime: {
    type: String,
    required: true,
  },
  division: {
    type: String,
    required: true,
  },
  homeTeamLong: {
    type: String,
    required: true,
  },
  homeTeamShort: {
    type: String,
    required: true,
  },
  homeTeamId: {
    type: String,
    required: true,
  },
  homeTeamScore: {
    type: Number,
    required: true,
  },
  homeTeamPreviousWins: {
    type: Number,
    required: true,
  },
  homeTeamPreviousLosses: {
    type: Number,
    required: true,
  },
  homeTeamPreviousTies: {
    type: Number,
    required: true,
  },
  homeTeamCurrentWins: {
    type: Number,
    required: true,
  },
  homeTeamCurrentLosses: {
    type: Number,
    required: true,
  },
  homeTeamCurrentTies: {
    type: Number,
    required: true,
  },
  homeTeamPreviousPoints: {
    type: Number,
    required: true,
  },
  homeTeamCurrentPoints: {
    type: Number,
    required: true,
  },
  visitorTeamLong: {
    type: String,
    required: true,
  },
  visitorTeamShort: {
    type: String,
    required: true,
  },
  visitorTeamId: {
    type: String,
    required: true,
  },
  visitorTeamScore: {
    type: Number,
    required: true,
  },
  visitorTeamPreviousWins: {
    type: Number,
    required: true,
  },
  visitorTeamPreviousLosses: {
    type: Number,
    required: true,
  },
  visitorTeamPreviousTies: {
    type: Number,
    required: true,
  },
  visitorTeamCurrentWins: {
    type: Number,
    required: true,
  },
  visitorTeamCurrentLosses: {
    type: Number,
    required: true,
  },
  visitorTeamCurrentTies: {
    type: Number,
    required: true,
  },
  visitorTeamPreviousPoints: {
    type: Number,
    required: true,
  },
  visitorTeamCurrentPoints: {
    type: Number,
    required: true,
  },
  winningTeamName: {
    type: String,
    required: true,
  },
  winningTeamId: {
    type: String,
    required: true,
  },
  losingTeamName: {
    type: String,
    required: true,
  },
  losingTeamId: {
    type: String,
    required: true,
  },
  tieResult: {
    type: Boolean,
    required: true,
  },
  week: {
    type: Number,
    required: true,
  },
});

//? TELLING MONGOOSE YOU WANT TO CREATE A MODEL USING OUR SCHEMA
const Scores = mongoose.model('Score', scoresSchema); //! Update Player and playerSchema for names that fit your application. Player is our model name and it MUST BE SINGULAR WITH AN UPPERCASE FIRST LETTER! mongoDB will then lowercase this model name and make it plural so it will change the name to ---> players

//? If miss adding fields to your schema for your original mongoose model you must add like this below
// mongoose.model('HockeyPlayer').schema.add({ division: String });

//? CREATION OF FIRST SET OF DATA FOR MongoDB DATABASE - Uncomment this out if you want this to populate your database with sample data
// const hockeyScores1 = Scores.insertMany([
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'Ontario Ice',
//     gameTime: '7:00am',
//     division: 'PeeWee',
//     visitorTeamLong: 'Lady Ducks',
//     visitorTeamShort: 'Lady Ducks',
//     visitorTeamId: 'pwladyducks1',
//     visitorTeamScore: 3,
//     visitorTeamPreviousWins: 2,
//     visitorTeamPreviousLosses: 5,
//     visitorTeamPreviousTies: 0,
//     visitorTeamCurrentWins: 3,
//     visitorTeamCurrentLosses: 5,
//     visitorTeamCurrentTies: 0,
//     visitorTeamPreviousPoints: 4,
//     visitorTeamCurrentPoints: 6,
//     homeTeamLong: 'Empire Hockey Club',
//     homeTeamShort: 'Empire',
//     homeTeamId: 'pwempire1',
//     homeTeamScore: 1,
//     homeTeamPreviousWins: 2,
//     homeTeamPreviousLosses: 8,
//     homeTeamPreviousTies: 1,
//     homeTeamCurrentWins: 2,
//     homeTeamCurrentLosses: 8,
//     homeTeamCurrentTies: 1,
//     homeTeamPreviousPoints: 5,
//     homeTeamCurrentPoints: 5,
//     winningTeamName: 'Lady Ducks',
//     winningTeamId: 'pwladyducks1',
//     losingTeamName: 'Empire',
//     losingTeamId: 'pwempire1',
//     tieResult: false,
//     week: 13,
//   },
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'KHS Ice',
//     gameTime: '9:50am',
//     division: 'PeeWee',
//     homeTeamLong: 'Jr. Ice Dogs',
//     homeTeamShort: 'Ice Dogs',
//     homeTeamId: 'pwicedogs1',
//     homeTeamScore: 7,
//     homeTeamPreviousWins: 5,
//     homeTeamPreviousLosses: 4,
//     homeTeamPreviousTies: 0,
//     homeTeamCurrentWins: 6,
//     homeTeamCurrentLosses: 4,
//     homeTeamCurrentTies: 0,
//     homeTeamPreviousPoints: 10,
//     homeTeamCurrentPoints: 12,
//     visitorTeamLong: 'Jr. Ducks (3)',
//     visitorTeamShort: 'Jr. Ducks',
//     visitorTeamId: 'pwducks3',
//     visitorTeamScore: 3,
//     visitorTeamPreviousWins: 1,
//     visitorTeamPreviousLosses: 7,
//     visitorTeamPreviousTies: 1,
//     visitorTeamCurrentWins: 1,
//     visitorTeamCurrentLosses: 8,
//     visitorTeamCurrentTies: 1,
//     visitorTeamPreviousPoints: 3,
//     visitorTeamCurrentPoints: 3,
//     winningTeamName: 'Ice Dogs',
//     winningTeamId: 'pwicedogs1',
//     losingTeamName: 'Jr. Ducks (3)',
//     losingTeamId: 'pwicedogs1',
//     tieResult: false,
//     week: 13,
//   },
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'La Jolla Ice',
//     gameTime: '11:45am',
//     division: 'PeeWee',
//     homeTeamLong: 'Saints',
//     homeTeamShort: 'Saints',
//     homeTeamId: 'pwsaints1',
//     homeTeamScore: 0,
//     homeTeamPreviousWins: 1,
//     homeTeamPreviousLosses: 9,
//     homeTeamPreviousTies: 0,
//     homeTeamCurrentWins: 1,
//     homeTeamCurrentLosses: 10,
//     homeTeamCurrentTies: 0,
//     homeTeamPreviousPoints: 2,
//     homeTeamCurrentPoints: 2,
//     visitorTeamLong: 'Jr. Ducks (2)',
//     visitorTeamShort: 'Ducks',
//     visitorTeamId: 'pwducks2',
//     visitorTeamScore: 6,
//     visitorTeamPreviousWins: 8,
//     visitorTeamPreviousLosses: 1,
//     visitorTeamPreviousTies: 1,
//     visitorTeamCurrentWins: 9,
//     visitorTeamCurrentLosses: 1,
//     visitorTeamCurrentTies: 1,
//     visitorTeamPreviousPoints: 17,
//     visitorTeamCurrentPoints: 19,
//     winningTeamName: 'Jr. Ducks (2)',
//     winningTeamId: 'pwducks2',
//     losingTeamName: 'Saints',
//     losingTeamId: 'pwsaints1',
//     tieResult: false,
//     week: 13,
//   },
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'Lakewood Ice',
//     gameTime: '12:30pm',
//     division: 'PeeWee',
//     homeTeamLong: 'Jr. Ducks (1)',
//     homeTeamShort: 'Ducks',
//     homeTeamId: 'pwducks1',
//     homeTeamScore: 5,
//     homeTeamPreviousWins: 4,
//     homeTeamPreviousLosses: 4,
//     homeTeamPreviousTies: 2,
//     homeTeamCurrentWins: 5,
//     homeTeamCurrentLosses: 4,
//     homeTeamCurrentTies: 2,
//     homeTeamPreviousPoints: 10,
//     homeTeamCurrentPoints: 12,
//     visitorTeamLong: 'Jr. Kings (2)',
//     visitorTeamShort: 'Kings',
//     visitorTeamId: 'pwkings2',
//     visitorTeamScore: 3,
//     visitorTeamPreviousWins: 8,
//     visitorTeamPreviousLosses: 0,
//     visitorTeamPreviousTies: 1,
//     visitorTeamCurrentWins: 8,
//     visitorTeamCurrentLosses: 1,
//     visitorTeamCurrentTies: 1,
//     visitorTeamPreviousPoints: 17,
//     visitorTeamCurrentPoints: 17,
//     winningTeamName: 'Jr. Ducks (3)',
//     winningTeamId: 'pwducks3',
//     losingTeamName: 'Jr. Kings (2)',
//     losingTeamId: 'pwkings2',
//     tieResult: false,
//     week: 13,
//   },
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'Lakewood Ice',
//     gameTime: '4:00pm',
//     division: 'PeeWee',
//     visitorTeamLong: 'California Heat',
//     visitorTeamShort: 'Heat',
//     visitorTeamId: 'pwheat1',
//     visitorTeamScore: 1,
//     visitorTeamPreviousWins: 6,
//     visitorTeamPreviousLosses: 3,
//     visitorTeamPreviousTies: 1,
//     visitorTeamCurrentWins: 6,
//     visitorTeamCurrentLosses: 4,
//     visitorTeamCurrentTies: 1,
//     visitorTeamPreviousPoints: 13,
//     visitorTeamCurrentPoints: 13,
//     homeTeamLong: 'Jr. Kings (1)',
//     homeTeamShort: 'Kings',
//     homeTeamId: 'pwkings1',
//     homeTeamScore: 5,
//     homeTeamPreviousWins: 7,
//     homeTeamPreviousLosses: 1,
//     homeTeamPreviousTies: 2,
//     homeTeamCurrentWins: 8,
//     homeTeamCurrentLosses: 1,
//     homeTeamCurrentTies: 2,
//     homeTeamPreviousPoints: 16,
//     homeTeamCurrentPoints: 18,
//     winningTeamName: 'Jr. Kings (1)',
//     winningTeamId: 'pwkings1',
//     losingTeamName: 'Heat',
//     losingTeamId: 'pwheat1',
//     tieResult: false,
//     week: 13,
//   },
//   {
//     season: '2021-2022',
//     gameDate: '01-30-2022',
//     venue: 'San Diego Ice',
//     gameTime: '4:50pm',
//     division: 'PeeWee',
//     visitorTeamLong: 'Goldrush Hockey Club',
//     visitorTeamShort: 'Goldrush',
//     visitorTeamId: 'pwgoldrush1',
//     visitorTeamScore: 7,
//     visitorTeamPreviousWins: 7,
//     visitorTeamPreviousLosses: 0,
//     visitorTeamPreviousTies: 2,
//     visitorTeamCurrentWins: 8,
//     visitorTeamCurrentLosses: 0,
//     visitorTeamCurrentTies: 2,
//     visitorTeamPreviousPoints: 16,
//     visitorTeamCurrentPoints: 18,
//     homeTeamLong: 'SDIA Hockey Club',
//     homeTeamShort: 'Oilers',
//     homeTeamId: 'pwoilers1',
//     homeTeamScore: 1,
//     homeTeamPreviousWins: 0,
//     homeTeamPreviousLosses: 9,
//     homeTeamPreviousTies: 0,
//     homeTeamCurrentWins: 0,
//     homeTeamCurrentLosses: 10,
//     homeTeamCurrentTies: 0,
//     homeTeamPreviousPoints: 0,
//     homeTeamCurrentPoints: 0,
//     winningTeamName: 'Goldrush',
//     winningTeamId: 'pwgoldrush1',
//     losingTeamName: 'Oilers',
//     losingTeamId: 'pwoilers1',
//     tieResult: false,
//     week: 13,
//   },
// ]).then((data) => console.log(data));

//? UPDATE RECORD
// HockeyPlayer.findOneAndUpdate(
//   { lastName: 'Gibson' },
//   {
//     height: 74,
//   }
// ).then((data) => console.log(data));

//? DELETION OF THE 1ST RECORD MONGOOSE FINDS IN MongoDB WITH THE SPECIFIED CRITERIA - Uncomment this out if you want to delete sample data above
// Player.findOneAndDelete({ firstName: 'Magic' }).then(data => console.log(data)); //! Change Player for a name that fits your application. Must do callback or it won't work.
// HockeyGameScore.findOneAndDelete({ season: '2021-2022' }).then((data) =>
//   console.log(data)
// );

module.exports = Scores; //! Change Player for name that fits your Application. This should be consistent with name given in line 31 of code above
