const mongoose = require('mongoose');

//? SETTING UP MongoDB SCHEMA
const standingsSchema = new mongoose.Schema({
  season: {
    type: String,
    required: true,
  },
  date: {
    type: String,
    required: true,
  },
  week: {
    type: Number,
    required: true,
  },
  division: {
    type: String,
    required: true,
  },
  team: {
    type: String,
    required: true,
  },
  wins: {
    type: Number,
    required: true,
  },
  losses: {
    type: Number,
    required: true,
  },
  ties: {
    type: Number,
    required: true,
  },
  gameResult: {
    type: String,
    required: true,
  },
  opponent: {
    type: String,
    required: true,
  },
});

//? TELLING MONGOOSE YOU WANT TO CREATE A MODEL USING OUR SCHEMA
const Standings = mongoose.model('Standings', standingsSchema);

//? CREATION OF FIRST SET OF DATA FOR MongoDB DATABASE - Uncomment this out if you want this to populate your database with sample data
// Standings.insertMany([
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Bears',
//     wins: 2,
//     losses: 1,
//     ties: 0,
//     gameResult: 'W',
//     opponent: 'Saints',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Ducks (1)',
//     wins: 0,
//     losses: 1,
//     ties: 2,
//     gameResult: 'T',
//     opponent: 'Heat',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Ducks (2)',
//     wins: 2,
//     losses: 1,
//     ties: 0,
//     gameResult: 'W',
//     opponent: 'Ice Dogs',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Ducks (3)',
//     wins: 1,
//     losses: 2,
//     ties: 0,
//     gameResult: 'L',
//     opponent: 'Goldrush',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Empire',
//     wins: 0,
//     losses: 3,
//     ties: 0,
//     gameResult: 'L',
//     opponent: 'Kings (1)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Goldrush',
//     wins: 2,
//     losses: 0,
//     ties: 0,
//     gameResult: 'W',
//     opponent: 'Ducks (3)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Heat',
//     wins: 2,
//     losses: 0,
//     ties: 1,
//     gameResult: 'T',
//     opponent: 'Ducks (1)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Ice Dogs',
//     wins: 2,
//     losses: 1,
//     ties: 0,
//     gameResult: 'L',
//     opponent: 'Ducks (2)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Kings (1)',
//     wins: 1,
//     losses: 1,
//     ties: 1,
//     gameResult: 'W',
//     opponent: 'Empire',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Kings (2)',
//     wins: 3,
//     losses: 0,
//     ties: 0,
//     gameResult: 'W',
//     opponent: 'Oilers',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Lady Ducks',
//     wins: 1,
//     losses: 1,
//     ties: 0,
//     gameResult: 'W',
//     opponent: 'Kings (2)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Oilers',
//     wins: 0,
//     losses: 3,
//     ties: 0,
//     gameResult: 'L',
//     opponent: 'Kings (2)',
//   },
//   {
//     season: '2021-2022',
//     date: '10-24-2021',
//     week: 3,
//     division: 'PeeWee',
//     team: 'Saints',
//     wins: 1,
//     losses: 2,
//     ties: 0,
//     gameResult: 'L',
//     opponent: 'Bears',
//   },
// ]);

module.exports = Standings;
